<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name>TextInOutUtils</name>
    <message>
        <location filename="../TextInOutUtils.py" line="235"/>
        <source>Test stopped on failure of rule: {ruleString}</source>
        <translation>Test wegen Regelfehlers abgebrochen: {ruleString}</translation>
    </message>
    <message>
        <location filename="../TextInOutUtils.py" line="327"/>
            <source>Run the {wildebeest} cleanup tool</source>
        <translation>F端hren Sie das {wildebeest}-Bereinigungstool aus</translation>
    </message>
    <message>
        <location filename="../TextInOutUtils.py" line="328"/>
        <source>help</source>
        <translation>Hilfe</translation>
    </message>
    <message>
        <location filename="../TextInOutUtils.py" line="526"/>
        <source>Test stopped on failure of rule {ruleNumber}: {ruleString}</source>
        <translation>Test wegen Nichterf端llung der Regel {ruleNumber} abgebrochen: {ruleString}</translation>
    </message>
    <message>
        <location filename="../TextInOutUtils.py" line="695"/>
        <source>Invalid File</source>
        <translation>Ung端ltige Datei</translation>
    </message>
    <message>
        <location filename="../TextInOutUtils.py" line="713"/>
        <source>Invalid Rules File</source>
        <translation>Ung端ltige Regeldatei</translation>
    </message>
</context>
</TS>
